### ISSUE TITLE
重みの初期化がよくわからない問題

### ISSUE THREAD

**Issue by nomuramasahir0** [bakanaouji/DeepQNetwork#1]
## 概要
`global_variables_initializer` の初期化が何に基づいているのかよくわからない

## 解決案
networkつくるときに明示的に指定したほうがいい気がする

**Comment by bakanaouji** [comment]
以下のような感じで修正するのがいいかな．
・DQNの重みってどうやって初期化するか論文に書いてあれば，それに合わせて初期化するように．
・書いてないのであれば，Open AIのコードを参考に．

**Comment by bakanaouji** [comment]
Open AIはxavier_initializationっていうので初期化している．
一方，kerasで何も指定していないとglorot_uniformっていうので初期化される．

**Comment by bakanaouji** [comment]
両方共，入力ユニット数をfan_inとし，出力ユニット数をfan_outとすると，[-sqrt(6 / (fan_in + fan_out)), -sqrt(6 / (fan_in + fan_out))]の範囲から一様ランダムに決定している．
なお，バイアス値は0初期化．

**Comment by bakanaouji** [comment]
ということで，同じ初期化方法なようなので，完了．
