### ISSUE TITLE
グレースケール化の変換式

### ISSUE THREAD

**Issue by bakanaouji** [bakanaouji/DeepQNetwork#10]
skimageのrgb2grayとopen aiの変換式が異なっている．
skimage : Y=0.2126R+0.7152G+0.0722B
open ai : Y=0.299R+0.587G+0.114B

**Comment by nomuramasahir0** [comment]
https://ja.wikipedia.org/wiki/%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B9%E3%82%B1%E3%83%BC%E3%83%AB

一応両方の方法があるらしいっすね

**Comment by bakanaouji** [comment]
そうなんすよ．用途によって違うみたいね

**Comment by bakanaouji** [comment]
グレースケール化した画像を保存してみたら、それっぽい画面になっていたので、たぶんOpen AI実装でいけるはず。
っていうか結果はほとんど変わらない気もします。
