### ISSUE TITLE
記事構成memo

### ISSUE THREAD

**Issue by nomuramasahir0** [bakanaouji/DeepQNetwork#13]
暫定的な記事構成めも

* 概要
* MDP
* 価値関数法
* Q-learning
* 関数近似
* DQN（とサーベイ)
* 実験

**Comment by nomuramasahir0** [comment]
先にq-learning, 関数近似，dqn書いて，必要な事前知識となるように価値関数法の説明

**Comment by nomuramasahir0** [comment]
ニューラルの説明どのくらいするか悩む

**Comment by bakanaouji** [comment]
DQNのこまごまとした各工夫の説明をどれだけ挟むのかも悩ましいね

**Comment by bakanaouji** [comment]
ニューラルの説明いれるとかなりカオスになりそう。
CNNってのがあるよくらいでいいんじゃないかな。
全体として強化学習の説明にはウェイト要れて、それ以外はサブの扱いで。
