### ISSUE TITLE
CNNモデルなどについて

### ISSUE THREAD

**Issue by Ni-coni-coni** [bakanaouji/DeepQNetwork#18]
研究にすごく役立ちました。レポジトリありがとうございます。
今はすでにつばめで実行できましたが、いくつ問題があります。
１.CNN第二層の設定でdata_format='channels_first'がないため、出力が(None, 15, 9, 64)になりましたが、多分間違ったと思います。
２.元論文と違って、第三層を抜けた原因は計算量を抑えるためでしょうか。
３.epsilonの最終値はなぜ0.01に設定していますか。元論文の0.1より効果が良いですか。

**Comment by bakanaouji** [comment]
質問ありがとうございます．以下，それぞれの点についての回答です．

１．単純なエンバグだったので，修正しました．

２．どこかの時点で消してしまっていたようです．ちなみに，第三層を抜いた場合の方がパラメータ数は多くなります．
第三層を入れると重みの総数は1,700,000個程度ですが，抜いた場合は2,700,000個程度になると思われます．なので，計算量的には第三層入れたほうが安いです．
ちなみに，第三層を抜いていて，かつ，１のバグ対処を行わないモデルの場合，重みの総数は4,400,000個程度で，さらに多くなっていました．
とりあえず，論文のモデルに合わせるように修正しました．

３．Open AIによる実装とパラメータを合わせているためです．
Pongのような簡単な問題の場合，学習の最後の方は探索を行う必要がおそらくほとんどないので，epsilonを論文値より小さな値にしても大きな影響はないと思われます．
一方でもっと難しい問題の場合，学習が進むのが遅いので，epsilonをある程度大きめの値にしておいて常に探索をさせることが重要になってくるので，その場合はepsilonを調整する必要があると思います．

**Comment by Ni-coni-coni** [comment]
わかりました．回答ありがとうございます！
