### ISSUE TITLE
[refactoring] tとepisodeが使われてる

### ISSUE THREAD

**Issue by nomuramasahir0** [bakanaouji/DeepQNetwork#2]
trainの方では `t`, testの方では `episode` が使われてるから統一したい

**Comment by bakanaouji** [comment]
終了条件をエピソード数で決定するということ？？

**Comment by bakanaouji** [comment]
tは総ステップ数，episodeは総エピソード数を表しているはずだけど，そこが何か違いますかね？

**Comment by nomuramasahir0** [comment]
あ，まちがえた
