### ISSUE TITLE
Q_Networkのinputのshapeが怪しい

### ISSUE THREAD

**Issue by bakanaouji** [bakanaouji/DeepQNetwork#5]
model.pyのtest_init_q_networkで初期化すると，modelのinputのshape=(?, 4, 84, 84)になる．
なんで不定にしてるのかを忘れた．

**Comment by nomuramasahir0** [comment]
グレースケール以外にも対応できるようにするためとか？

**Comment by bakanaouji** [comment]
その可能性はあるね、現状では問題なさそうなので、据え置きかな

**Comment by bakanaouji** [comment]
グレースケールのみの対応でいい気がするし、なんかうまく動かなかったので、shape=(1, 4, 84, 84)にしました。
