### ISSUE TITLE
gym.envのpongとbreakoutの行動数が6

### ISSUE THREAD

**Issue by bakanaouji** [bakanaouji/DeepQNetwork#8]
本来pongとbreakoutは行動は[何もしない，上（左），下（右）]の３つであるはずだが，なぜかenv.actionspaceはDiscrete(6)を返す．

**Comment by nomuramasahir0** [comment]
http://taotao54321.hatenablog.com/entry/2016/11/12/011955

```
値	意味
0,1	何もしない
2,4	上へ移動
3,5	下へ移動
```

これかも

**Comment by bakanaouji** [comment]
それは自分の環境でも調べてみて確認してみました。
問題はなぜ同じ行動が２つずつ存在するのかということ。。。

**Comment by bakanaouji** [comment]
breakoutは4つでした

**Comment by bakanaouji** [comment]
pongに関しては、
0 : 何もしない
1 : Fire（何もしない）
2  : 上へ移動
3 : 下へ移動
4 : FireRight（上へ移動）
5 : FireLeft（下へ移動）

**Comment by bakanaouji** [comment]
Fireはエピソード開始時にゲームを始めるためのコマンド。

**Comment by bakanaouji** [comment]
わざわざこのために行動数を増やすのもばかばかしい気もする。。。
